name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pkg
        run: npm i -g pkg

      - name: Build
        run: ARCHES="${{ matrix.arch }}" bash build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/appimage-manager-linux-${{ matrix.arch }}
          generate_release_notes: true
